version: 2

defaults: &defaults
  working_directory: ~/project/ycsaudio
  docker:
    - image: banian/node

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: ~/project
          paths:
            - ycsaudio

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Lint
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Test
          command: yarn test && yarn codecov

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy To Github Pages
          command: yarn deploy-ghpages

workflows:
  version: 2
  setup-and-parallel-test:
    jobs:
      - setup

      - lint:
          requires:
            - setup

      - test:
          requires:
            - setup

      - deploy:
          requires:
            - setup
          filters:
            branches:
              only:
                - master
